---

- name: Lstu | Update apt cache
  apt: update_cache=yes cache_valid_time=86400
  changed_when: no

- name: Lstu | Install essential packages
  apt: name="{{ item }}" state=present
  with_items:
    - build-essential
    - git
    - libssl-dev
    - libpng-dev # for QR code generation
    - libpq-dev # required for Mojo::PG (even if PGSQL won't be used)
    - libmysqld-dev # required for Mojo::mysql (even if MySQL won't be used)

- name: Lstu | Install cpanm
  get_url:
    url: https://cpanmin.us
    dest: /usr/local/bin/cpanm
    mode: 0555

- name: Lstu | Install Carton
  command: creates=/usr/local/bin/carton cpanm Carton
