---

- name: Lstu | Create working directory
  file:
    dest: "{{ lstu_working_dir }}"
    state: directory

- name: Lstu | Checkout git repository
  git:
    repo: https://framagit.org/noplanman/lstu.git
    dest: "{{ lstu_working_dir }}"
    update: "{{ lstu_keep_updated }}"
  register: lstu_git_updated
  notify: restart lstu

- name: Lstu | Copy config
  template:
    src: lstu.conf.j2
    dest: "{{ lstu_working_dir }}/lstu.conf"
    mode: 0644
  notify: restart lstu

- name: Lstu | Install lstu
  command: carton install
  args:
    chdir: "{{ lstu_working_dir }}"
  when: lstu_git_updated.changed
  notify: restart lstu

- name: Lstu | Set permissions on working directory
  file:
    path: "{{ lstu_working_dir }}"
    state: directory
    owner: "{{ lstu_user }}"
    group: "{{ lstu_group }}"
    recurse: yes
